PDF =								pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.pdf

all:								pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.pdf

pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.pdf:	pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.tex \
								pesquisa_linear/grafico.jpg \
								pesquisa_linear/main.c \
								pesquisa_linear/pesquisa_linear.c \
								pesquisa_linear/curva-inicio.txt \
								bubble_sort/grafico1.jpg \
								bubble_sort/grafico2.jpg \
								bubble_sort/main.c \
								bubble_sort/bubble_sort1.c \
								bubble_sort/bubble_sort2.c \
								graficos/10n.gnuplot \
								graficos/10n.jpg \
								graficos/1.gnuplot \
								graficos/1.jpg \
								graficos/2^n.gnuplot \
								graficos/2^n.jpg \
								graficos/grupo1.gnuplot \
								graficos/grupo1.jpg \
								graficos/grupo2.gnuplot \
								graficos/grupo2.jpg \
								graficos/grupo3.gnuplot \
								graficos/grupo3.jpg \
								graficos/log_n.gnuplot \
								graficos/log_n.jpg \
								graficos/n^2.gnuplot \
								graficos/n^2.jpg \
								graficos/n^3.gnuplot \
								graficos/n^3.jpg \
								graficos/n.gnuplot \
								graficos/n.jpg \
								graficos/n_log_n.gnuplot \
								graficos/n_log_n.jpg \
								graficos/nxn.gnuplot \
								graficos/nxn.jpg \
								graficos/todas.gnuplot \
								graficos/todas.jpg
								@pdflatex -shell-escape pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.tex
								@pdflatex -shell-escape pucrs-ec-poo-unidade_01-complexidade_de_algoritmos-laminas.tex

clean:
	@rm -f *~ *.pyg *.log *.out *.aux *.toc *.nav *.snm *.vrb
	@rm -rf _minted-*
